Repository Eduhub-Community/eduhub-website, pull requests merged in 2021-10, with the labels that each got.

#71 fix arrow to make it visible
  css/main.css
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#69 Changes made in team section
  css/main.css
  index.html
Labels: help wanted, Hacktoberfest2021

#73 Added Fixes and Changes
  img/teleram icon.png
  img/works/event-12.jpeg
  index.html
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#72 Links updated and #back-top updated
  css/main.css
  index.html
Labels: good first issue, Hacktoberfest2021, Hacktoberfest-accepted

#78 Fixed button layout
  css/main.css
  index.html
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#79 Social media icons are now visible properly.
  css/main.css
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#75 fixed the home-screen social icons and applied hover effect(red) on them
  css/main.css
  index.html
Labels: Hacktoberfest2021

#84 2 sections added
  css/main.css
  img/CommunityPartners/SSIT.jpeg
  img/CommunityPartners/abes.jpeg
  img/CommunityPartners/dataprotocol.jpeg
  img/CommunityPartners/givemycertificate.jpeg
  img/CommunityPartners/givemycertificate.png
  img/CommunityPartners/gu.jpeg
  img/CommunityPartners/iiitb.jpeg
  img/CommunityPartners/lpu.jpeg
  img/CommunityPartners/nie.jpeg
  img/CommunityPartners/rgukt.jpeg
  img/CommunityPartners/sist.jpeg
  img/CommunityPartners/ski.jpeg
  img/CommunityPartners/soa.jpeg
  img/CommunityPartners/uem.jpeg
  img/CommunityPartners/vit.jpeg
  img/CommunityPartners/vssut.jpeg
  index.html
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#87 UI UPDATES
  css/main.css
  index.html
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#89 Made Team section Responsive
  css/main.css
  index.html
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#99 Update social media icon
  index.html
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#102 Font Awesome icons improvisation
  index.html
Labels: enhancement, Hacktoberfest2021, Hacktoberfest-accepted

#110 Testimonial section made responsive and sliding effect added
  css/testimonial.css
  js/testimonial.js
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#111 Added custom styling and hover effect to main buttons
  css/main.css
  index.html
Labels: enhancement, Hacktoberfest2021, Hacktoberfest-accepted

#112 Added a blog posts section.
  css/blogPosts.css
  img/blogPosts/blog1.jpg
  img/blogPosts/blog2.jpg
  img/blogPosts/blog3.jpg
  index.html
Labels: enhancement, Hacktoberfest2021, Hacktoberfest-accepted

#115 add animated slider image in front page
  css/bootstrap.min.css
  css/main.css
  index.html
  team.jpg
Labels: enhancement, Hacktoberfest2021

#119 Z-index of side elements changed
  css/main.css
Labels: Hacktoberfest2021, Hacktoberfest-accepted

#136 Appealing scroll bar #135
  css/main.css
Labels: Hacktoberfest2021, Hacktoberfest-accepted
